sudo: false
language: python
python:
  - 3.5
  - 3.6
  - 3.7
matrix:
  include: # Required for python 3.7+
    - python: 3.7.3
      dist: xenial
    - python: 3.8
      dist: xenial
install:
  - pip install poetry # 在初始化时安装所需要的依赖，另一种方式：- pip install requirements.txt
  - poetry install -vvv
script:
  #- pytest mubu_login.py
  # 加上 poetry run 指定在 poetry 虚拟环境中执行
  - poetry run coverage run --source=httprunner-shijian -m pytest
  - poetry run coverage report
after_success:
  # - poetry run coveralls
  # - python -m httprunner.cli hrun -h
  # - poetry bulid
  # - poetry run coverage --source=httprunner -m unittest discover
# after_success:
  # - poetry run coveralls
  - poetry run coverage run --source=httprunner-shijian/tests -m pytest